config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users

  root :to => "homes#top"
  get "home/about" => "homes#about"

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings"
    get "followers" => "relationships#followers"
  end
  
  get "searches" => "searches#search"
  
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  scope :order_updated_desc, -> { order(updated_at: :desc) }
  scope :order_rate_desc, -> { order(rate: :desc) }
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.search_for(keyword, search, column)
    
    # 完全一致検索
    if search == "perfect_match"
      Book.where("#{column}": keyword)
    # 前方一致検索
    elsif search == "forward_match"
      Book.where("#{column} LIKE ?", "#{keyword}%")
    # 後方一致検索
    elsif search == "backward_match"
      Book.where("#{column} LIKE ?", "%#{keyword}")
    # 部分一致検索
    elsif search == "partial_match"
      Book.where("#{column} LIKE ?", "%#{keyword}%")
    # それ以外
    else
      Book.none
    end
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :is_matching_login_user, only: [:edit, :update]

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new
    if params[:order_updated_desc]
      @books = Book.order_updated_desc
    elsif params[:order_rate_desc]
      @books = Book.order_rate_desc
    else
      @books = Book.all
    end
    
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.rate = book_rate_params[:rate] unless book_rate_params[:rate].empty?
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :tag)
  end
  
  def book_rate_params
    params.permit(:rate)
  end
  
  def is_matching_login_user
    user_id = Book.find(params[:id]).user.id.to_i
    login_user_id = current_user.id
    if(user_id != login_user_id)
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book_rate.html.erb
<div id='book-rate-<%= book.id %>'></div>
<script>
$(document).on('turbolinks:load', function () {
  $('#book-rate-<%= book.id %>').empty();
  // scriptファイルをどのidの部分に配置するかを指定
  let elem<%= book.id %> = document.querySelector('#book-rate-<%= book.id %>');
  let opt<%= book.id %> = {
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn :  '<%= asset_path('star-on.png') %>',
    score: <%= book.rate %>,
    readOnly: true
  };
  raty(elem<%= book.id %>,opt<%= book.id %>);
});
</script>

app/views/books/_form.html.erb
<%= form_with model: book, local: true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body, "Opinion" %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class="form-group" id="post_rate">
    <%= f.label :rate %>
    <%= f.hidden_field :rate, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :tag %>
    <%= f.text_field :tag, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>
<script>
$(document).on('turbolinks:load', function () {
  $('#post_rate').empty();
  // scriptファイルをどのidの部分に配置するかを指定
  let elem = document.querySelector('#post_rate');
  let opt = {
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn :  '<%= asset_path('star-on.png') %>',
    scoreName: 'rate'
  };
  raty(elem,opt);
});
</script>

app/views/books/_index.html.erb
<% if books.exists? %>
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Tag</th>
      <th>Favorite</th>
      <th>Comment</th>
      <th>Rate</th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td>
          <%= link_to book.title, book %>
        </td>
        <td>
          <%= book.body %>
        </td>
        <td>
          <% if book.tag.present? %>
            <%= link_to book.tag, searches_path(keyword: book.tag, tag: "true") %>
          <% end %>
        </td>
        <td class="favorite-btn-<%= book.id %>">
          <%= render 'favorites/favorite-btn', book: book %>
        </td>
        <td>
          コメント数:<%= book.book_comments.count %>
        </td>
        <td>
          <%= render 'books/book_rate', book: book %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>投稿は存在しません</p>
<% end %>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= link_to '新しい順', books_path(order_updated_desc: "true") %> |
      <%= link_to '評価の高い順', books_path(order_rate_desc: "true") %>
      <%= render 'index', books: @books%>
      
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th>Tag</th>
          <th>Favorite</th>
          <th>Comment</th>
          <th>Rate</th>
          <th></th>
          <th></th>
        </tr>
  		  <tr>
          <td>
            <%= link_to(@book.user) do %>
              <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
              <%= @book.user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to @book.title, @book %>
          </td>
          <td>
            <%= @book.body %>
          </td>
          <td>
            <% if @book.tag.present? %>
              <%= link_to @book.tag, searches_path(keyword: @book.tag, tag: "true") %>
            <% end %>
          </td>
          <td class="favorite-btn-<%= @book.id %>">
            <%= render 'favorites/favorite-btn', book: @book %>
          </td>
          <td class="comment_count">
            コメント数:<%= @book.book_comments.count %>
          </td>
          <td>
            <%= render 'books/book_rate', book: @book %>
          </td>
          <% if @book.user == current_user %>
          <td>
            <%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %>
          </td>
          <td>
            <%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger" %>
          </td>
          <% end %>
        </tr>
      </table>
      
      <h2>Comments</h2>
      <%= render 'book_comments/index', book: @book %>
      <%= render 'book_comments/form', book: @book, book_comment: @book_comment %>
      
    </div>
  </div>
</div>